### ISSUE TITLE
Access permission table

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/PHES-ODM#100]
In the past week I have been transferring historic data to the Quebec template. One thing that struck me is the number of fields we have for the `WWMeasure` and `SiteMeasure` tables that are the same for each record. 

One opportunity I see to reduce the copying and pasting is to move the access permission fields to a separate table (e.g. `AccessPermissions`) so that we can refer to an ID rather than having to repeat the same information over and over. I guess this would not necessarily be a breaking change, no?

**Comment by DougManuel** [comment]
Would a separate table allow permissions for specific measures?

A good template should repopulate cutting and pasting with defaults.

**Comment by NielsNicolai** [comment]
Hi @DougManuel. The idea of having a separate table is indeed to reduce the copy and pasting. Imagine an 'AccessPermission' table that for which the first (and default) record is one that grants access to all partners. It would make things much more neat.

**Comment by hswerdfe** [comment]
I think this is a big change and would put it at lower priority.

**Comment by NielsNicolai** [comment]
@hswerdfe Why do you consider this a major change? And if so, wouldn't it be better if we do it now before things might get even more complicated in the future?

**Comment by hswerdfe** [comment]
its an additional table, which is not even fully fleshed out yet.

**Comment by NielsNicolai** [comment]
My feeling says it's worth the change. At the moment it creates a lot of overhead, but I also don't want to remove it from the Excel template as people need to understand that their data will be public or not.

**Comment by hswerdfe** [comment]
@NielsNicolai  why don't you make a branch and propose what it would look like. because it is not clear to me what the final result would be.

**Comment by mathew-thomson** [comment]
Currently the access permissions table has been deprecated in favour of moving everything over to a sharing schema, with details findable in the sharing branch. Closing this issue for now, though it can be reopened if the issues with sharing/the sharing schema persist in this vein.
