### ISSUE TITLE
Formats for variables

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#101]
Add greater format details for variables. 

1) ArgGIS has limitations on some data lengths.
2) Provide specifics.

Incorporate formats in two places.
- Variables and VariableCategories - for specific format requirements. The preference is to use this approach to allow machine-actionable format validation.
- metadata.md — for general considerations

**Comment by hswerdfe** [comment]
I will add these to the tables ? Then they will  then add them to the metadata generators.

**Comment by hswerdfe** [comment]
I am testing to see what it looks like this is what I see for **Reporter** table with some validations....comments ?

![image](https://user-images.githubusercontent.com/19482839/109703391-69169b00-7b63-11eb-8190-de581f998731.png)

**Comment by hswerdfe** [comment]
yah, I was thinking about writing them in `English`, but then I thought I need a second column for validation rules in `French`. I've done that before, where you read in a string that is an R code bit and you can execute it directly. it makes building and maintaining a validator easier. 

I am almost sure the same could be done for python. do you have opinions on validation?

**Comment by hswerdfe** [comment]
- English or french readable rules
 - rules on variables in variables
 - rules on multiple variables in seperate table
 - generate variables validation rules.md

**Comment by mathew-thomson** [comment]
These formats on maximum and minimum length and maximum and minimum values have been implemented as columns in the parts list. This (along with the variable type column) specifies out the formats for variables in adequate detail.
