### ISSUE TITLE
Storing polygons as geoJSON instead of WKT?

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#115]
On the Québec side, a lot of our collaborators are using geoJSON and the conversion to wkt and back is causing some friction. geoJSON is also easier to transfer into arcGIS and back, and it is natively supported by most visualization libraries, whereas wkt usually has to be parsed and converted before use. Thoughts? :)

**Comment by DougManuel** [comment]
Geo data needs a larger discussion with users. Ontario is using arcGIS and I had the same concerns. We want an open format.

**Comment by hswerdfe** [comment]
geoJSON seems fine to me.

**Comment by mathew-thomson** [comment]
Linking this to issue #87 - GeoJSON seems like a good option, especially as there are tools/packages available to change file formatting should the need arise (example: https://gdal.org/programs/ogr2ogr.html)

**Comment by mathew-thomson** [comment]
See my previous comment, issue closed.
