### ISSUE TITLE
Add mutations, in addition to variants

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#120]
In some situations, there are mutations like E484 that are clinically important that span variants/linages (P.1, B1.351). 

Should we add mutation parameters? Seems straightforward?

**Comment by jeandavidt** [comment]
Would that simply be a new `type` of measurement?

**Comment by DougManuel** [comment]
We are working on improving variant reporting. A few preliminary comments:

1) WWMeasure table is the place to put variant measures.

1) Additional provisions for variant names is needed. One variant or mutation label per measurement will be much easier to implement than using multiple labels per measure. Is this possible?  
Nexclade or Pangolin =  👍.      Nexclade and Pangolin = 😟.

1) There are already many many helpful `unit` and `aggregation` measures that work well for variants. However, additions are needed. 
- Several additional `unit` measures will be required. No problem. Additions identified so far include: `coverage`, `mutationsAssessed`, `mutationsFound`, `reads`, `importantMutations`. Stay tuned. Comments and addtions welcomed.
- Several additional `aggregation` measures identified so far. `depth`, `detectionLevel`. We are missing a few other general measures, `CI05`, `CI95`.

**Comment by DougManuel** [comment]
4. Samples can have multiple mutations, and mutations can be at different proportions or levels. These could be handled as:
-  individual measurements but then we need to be able to combine in a wide table, which requires a new `index` variable, I think. Something like `listIndex`. As well, we can use `value` for different proportions or levels but we'll need to have category levels within `value`. 
- a separate table for variant mutations. Is it worth the effort?
- have lists as `value` or similar variables. We have only done that once before -- I think for postal code/zip code. I suggest that we stay away from lists if there are other reasonable alternatives.

**Comment by DougManuel** [comment]
Notes from a discussion with @jeandavidt 

1) Introduce `subType`? Including subtypeNexus, subtypePangolin, subtypeMutation, subtypeQC
1) Introduce category values. For VOCs there are currently proposed categories for subconsensus such as high, med, low. We will need to be explicit about category values (machine actionable), which could be added to variables or variableCategories.
1) Introduce nicknames for wide table variables.
1) hmm. Something about units and aggregations. @jeandavidt  do you remember?

**Comment by rnaguru** [comment]
> 2. Additional provisions for variant names is needed. These would be added to `type`. One variant or mutation label per measurement will be much easier to implement than using multiple labels per measure. Is this possible?

^This. At least for PCR tests it looks like we should be moving towards mutation/allele-centric notation rather than lineage-centric. The former is unambiguous. 

Is there a desire to capture the raw data as well as the proportional expression? If so, there are additional measures and currently two different PCR methods used (Delatolla vs. Servos lab methods) to derive proportional expression.

**Comment by rnaguru** [comment]
For Seq data, lists of individual mutations might be overkill. Minimal variables for a sequencing run might be as follows:

```
sampleDate
```
siteID
siteName
reportDate
sampleType
assayID. [e.g. Articv3_Illumina]
seqQC_N1 [qPCR of sample for sequencing]
seqQC_breadth [genome coverage measure]
seqQC_depth [genome coverage measure]
[pango lineage]_detection confidence

[pango lineage]_proportionExpQual
[pango lineage]_proportionExpQuant

[pango lineage]_mutations

**Comment by mathew-thomson** [comment]
For something like this, @jeandavidt suggested adding "lineage" as a measure, that could then be linked to a nomenclature (like Pangolin). `sampleDate`, `siteID`, `siteName`, `reportDate`, `sampleType`, `assayID`, and `seqQC_N1` are all captured in some way or another in the current structure for version 2, but QC measures of breadth and depth might still need to be added (likely just as regular measures, and the the `purpose` field could be populated with "QC"). For listing the mutations though, it's a little more complicated. Short of creating an ID for every mutation, or including them as a list, JD also suggested allowing users to add mutation reports as BLOB, or JSON, or whatever file format folks are using in the field. Do people have thoughts on this?

**Comment by DougManuel** [comment]
From Ontario's Wastewater Surveillance Initiative: proposed reporting measures:
- Ct (from N1)

- % Breath of covers (>= 5x depth)

- average depth of coverage

- median depth of coverage

-  variant frequency detected (not sure if this is the proportion of the variant)

**Comment by mathew-thomson** [comment]
Continuing on this thread, we do have the attribute "lineage" which would apply to variants, as stated above. But it would be useful to have a better understanding of what kinds of values this variable would take. Ideally I think it would be a categorical variable to avoid having the data be a mess. Would other variants (ie: omicron, delta, and alpha) be the values? It would helpful to know what labs are currently reporting as the lineage.

**Comment by rnaguru** [comment]
> Building off this, in today's meeting it was decided that it might be best to have a unique measure ID for each mutation. These will be connected to `lineage` and `nomenclature`, of course. There is already a potential list in the values for PCR gene target in NWSS's latest version.

possible to use similar attributes as LAPIS (https://lapis.cov-spectrum.org/#introduction) that is used for https://cov-spectrum.org? But also have frequency attached to each mutation in the list?
