### ISSUE TITLE
CPHD additional variable types

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#129]
I'm parsing the Quebec Public Health Data (from INSPQ), and there are some types of data that I can't fit into the categories available in the ODM:

Suggestions:
1. A column indicating whether a value records a *daily count*, a *cumulative count*, or a *rate* (per 100k), as having all of them gathered in the `type` column can get very confusing.
2. Additional value types:
    - Deaths
    - Recovered
    - Distinguishing between *regular* hospitalisations vs. *intensive care* visits.

**Comment by mathew-thomson** [comment]
I think this issue is related to issue #215 - where these measures would be captured as population measures/units now. Is this accurate? Does more still need to be done to address this issue?

**Comment by jeandavidt** [comment]
We would just need to create the appropriate population measures:
- `cov19Recovered`
- `cov19Deaths`
- `cov19ICUAdmission`
- `cov19HospAdmission` ?

**Comment by mathew-thomson** [comment]
I think we already have `hospAdm` and `hospCen` but these have been included as units. I can add `Recovered`, `Deaths`, and `ICU` though. My only thought/concern is whether these should continue to be treated as units for the measure of `population`, or whether they should be measures in their own right?

**Comment by jeandavidt** [comment]
I think that makes sense!

**Comment by jeandavidt** [comment]
It feels like it makes sense. would these aggregations be gathered in a set? If so, would that set also include the usual suspects for linear measurements (mean, median, standard dev, ...)? 

I feel like these two concepts (statistics like mean and aggregated measures like cumulative counts or rate per 100k) may be semantically a bit different? Not sure how to best address that

**Comment by mathew-thomson** [comment]
I think it makes sense to put them into an aggregation set - likely one that is distinct for the other "true" statistical aggregations, like you mention. Currently we have boolean aggregations, linear aggregations, and logarithmic aggregations as sets, and I was thinking of creating a set called 'population aggregations' or something to that effect for these kinds of aggregations? To highlight the distinction that you bring up.

I agree that they're semantically different, but I would argue that they differ from the other aggregations in the same way a unit like "deaths" differs from any SI unit like mm or kg. I think short of of making deaths, ICU, hospitalizations, etc. into measures, theres no real way of capturing both of these pieces of metadata in one line. Even if we did move these from units to measures, where would the covid19 piece get captured in the data? I know it's a little messy, but I think it may be what makes the most sense within the structure that we have?

**Comment by DougManuel** [comment]
Yes, any 'group' can have a 'population' class as well, there can be a 'disease' class. So, SARS-CoV-2 can have 'cov' for Covid-19. There are provisions for more specific forms of Covid-19 such as long Covid-19. The disease class may be more important for other infections, say, tuberculosis. 

For population measures, the total count or rate per 100k seems like units. I don't think we have a rate per 100K as a unit currently, but we can (and should) add that.

**Comment by DougManuel** [comment]
Population metrics are part of ODM V2. 

Measures or observations for populations are identified as `specimen = population`. Measures or observations for people are identified as `compartment = human`. As for any measure, there must be a unit. The `populationUnitSet` applies. The list of population units are below. They can be expanded to include, say, cases for age groups or gender.

**Specimens**
partID | label
-- | --
po | Population
sa | Sample
si | Site

**Compartments**
partID | label
-- | --
a | Air compartment
h | Human compartment
s | Surface compartment
w | Water compartment
naCompartment | Compartment not applicable

**Population Unit Set**
partID | label
acti | Number of active cases
conCase | Confirmed Cases Case Report Date
conf | Number of confirmed cases
confEp | Confirmed cases episode date
confOn | Confirmed Cases Onset Date
conTest | Confirmed Cases Test Date
hosa | General Hospital Admissions
hosc | Hospital Census
icu | Intensive care unit patients
newVax | Population of newly vaccinated persons
pprt | Percent positivity rate
ptot | Number of positive tests
test | Number of tests performed
vax1 | Population with 1 dose of vaccine
vax2 | Population with 2 doses of vaccine
rP100 | Rate per 100,000
recov | Recovered patients
daiCo | Daily count
death | Deaths
cuCo | Cumulative count
vax3 | Population with 3 doses of vaccine
