### ISSUE TITLE
LOD part 2

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#130]
Labs are unsure how to report low detect values. There is not a consistent approach. Most commonly, labs write notes about LOD with a 0.00 value entered. 

Suggest that we revisit how LOD is reported in `wwMeaasure`. 

@vipileggi  is this correct?

**Comment by DougManuel** [comment]
See also #11.

**Comment by vipileggi** [comment]
@DougManuel Yes, and also people are reporting these values by writing in '<LOD' in the `value`. One current strategy I'm considering is to replace all values reported that are <LOD with 1/2 LOD (US CDC](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/wastewater-surveillance/data-reporting-analytics.html).
> Include wastewater samples with SARS-CoV-2 levels below the limit of detection in trend calculations. This can be done by assigning the sample a value of half the assay detection limit.

 So, if we implement the US CDC recommendation (introduces some bias but considered minimal and of no major significance 
 since it would affect only the 'no actionable situations'; I think) the reported LOD in the 'assayMethod' worksheet can be used to replace reported values.

**Comment by DougManuel** [comment]
The first step is to provide better support for LOD in the data dictionary. It is time to add terms and variables if people are commonly using notes for the same topic.

Assigning values (such as half values) is later in the process of data cleaning, transformation, and validation. An analyst may want to use different approaches that should all be supported by the dictionary.

**Comment by DougManuel** [comment]
What about adding a new variable: `belowLOD` or similar. Allowed input would be TRUE/FALSE.

Guidance on what to put in the `value` field is important. A challenge is a lack of a common approach for missing data in different data formats. What to enter and types of missing data is a topic that we've avoided but needs to be addressed. Given
Excel is the most common use, we probably need to simply say missing data in the ODM is blank.

**Comment by vipileggi** [comment]
Alex Chick from OCWA-MECP is leading a detailed review of issues surrounding 'LOD' which should include how best labs should report on values < LOD. He's also planning to write this up shortly and labs will have an opportunity to comment. I think we can use this new document to inform this issue. I will find out the status of Alex's review. Having a new variable may be a good way to simplify reporting these values. But to avoid potential loss of information we then need a consistent rule on how we use this T/F information to compute on it; unless we choose to ignore these values for computing average values and use this information in some other way (a frequency table). Then how we do reconcile the US CDC recommendation of substituting LOD/2?

**Comment by mathew-thomson** [comment]
I mentioned this over in issue #209, but does our PCR quality flag of 'ND' with a zero value for the measure cover off this issue, or do we need a more tailored approach to addressing LOD still?

**Comment by mathew-thomson** [comment]
In today's meeting it was discussed and we believe that yes, this has been sufficiently covered off.
