### ISSUE TITLE
Sample condition - new variable request

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#131]
Add a new sample variable for the sample condition. Suggest `condition` in the Sample table.

categories:
- leaked

@cmangat, does this variable reflect your practice. Are there other categories?

**Comment by mathew-thomson** [comment]
A quality set of 'sampleQuality' has been added to the dictionary for version 2. Currently the flags are: 

- leaked
- wrong temperature
- stored incorrectly

Are there any others that should be added, @cmangat? I also think 'wrong temperature' and 'stored incorrectly' may be duplicative.

**Comment by mathew-thomson** [comment]
See above comment
