### ISSUE TITLE
Difference between uWWMeasureID and WWMeasureID?

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#134]
In the `site/Variables.csv` file, there are 2 IDs defined for the `WWMeasure` table: `uWwMeasureID`and `wwMeasureID`.

`uWwMeasureID` is said to be for the long table format, while `wwMeasureID`is for the wide table format.

During our Thursday ODM meeting, we weren't sure why both were defined in the `Variables.csv`file. 

Since the wide table is not explicitly defined because the columns depend on what data is being collected, should the `Variables.csv` file contain the wide table id?

On the implementation side, should both long and wide tables have columns for both IDs or should they simply have one column the ID defined for their format?

**Comment by mathew-thomson** [comment]
I'm closing this issue because these tables no longer exist in version 2, and so this issue is no longer applicable for this stage of the work. More discussion on wide table variables and consistency can be migrated over to issue #128
