### ISSUE TITLE
WWmeasure value as a float type

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#143]
Are we comfortable with `value` being a float type? 

For at least one measure we allow a boolean response? 
WWMeasure > unit = detected,  where 1 = detected and 0=not detected
We also have a boolean unit (`bool`) but we do not specify the boolean values. At a minimum, we should. 1 = TRUE, 0 = false?

I ask because we may need a categorical response in for variant testing. Currently, the National Microbiology Lab in Canada uses "low", "med", "high" etc. to describe the level of mutation in a sample. We can add as a float (i.e 1 = low), but I was wondering....

On the balance, I think it makes sense to keep as a float, but there are other options... I a reluctant to stay we would have type as text because then we need to coerse most values.  We could also be explicit and have valueFloat, valueText, valueBoolean, but that causes other issues.

**Comment by jeandavidt** [comment]
Hm!
I think I would keep the `value` field as a float, but the unit needs to be more explicit to avoid misinterpretation.
maybe something like `qualitativeScale1to3` for this particular case?

We could provide a few qualitative scales like that one in the basic data dictionary, but if a user uses different ones (say, theirs starts at zero, or they have more or fewer levels), as long as they stick to this naming convention they could add them to `unitOther` and be easily understood by other users ¯\_(ツ)_/¯ 

For the boolean values, it's true that we don't explicitly specify them, but the fact that the value has to be a float make it fairly intuitive imo.

But the fact that both `bool` and `detected` (which is just a bool) are present seems a bit weird. Maybe we should remove `detected` and use `bool` for everything boolean? Or we could let the unit be more specific but also make it clearer that it is in fact boolean, as in `detectedBool`...

**Comment by DougManuel** [comment]
I actually think it is odd that we have `bool` since that is a type and not an aggregator or unit. I don't know when someone would use that aggregator. The CDC NWSS has a nice approach where they have predefined categories like the quantitative scales that you identify.

Let's keep as value as a float for now.

**Comment by mathew-thomson** [comment]
Current discussion around data type are on going, but I think mostly resolved (by and large). wwmeasure as a table no longer exists, but the data type for value will be "any" as it will be a category, integer, or boolean depending on the measure/method in question. Closing this issue for now as I believe it to be resolved.
