### ISSUE TITLE
Renaming `assayID` to assayMethodID`in `WWMeasure`

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#148]
For the sake of consistency, and to avoid name collisions in the event that an `Assay` table is added

**Comment by sorinsion** [comment]
Please update the ODM/src/wbe_create_table_SQLITE_en.sql as well

**Comment by mathew-thomson** [comment]
Flagging to revisit this issue once the V2.0 dictionary is better fleshed out (maybe tomorrow?)

**Comment by mathew-thomson** [comment]
There is no longer an "assay" distinction in the dictionary. Instead values/variables of this type are treated and called as either methods or measures. As such, I am closing this issue because it is no longer relevant.
