### ISSUE TITLE
Removing "Default" fields in Schema

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#171]
Maybe "Default" fields (e.g., `SampleCollectionDefault`, `MeasureFractionAnalyzedDefault`, ...) belong in a config file rather that in the structure of the model itself, as they: 
* repeat variables found elsewhere in the ODM
* are not always consistent (not everything has a default)
* may cause difficult-to-catch errors (if the fields are not often used, there may be out-of-date info in them.)
* may complicate validation.

Having these defaults in the mapper configuration files would allow ODM users to still have default values if they wish, but without adding possibly confusing data to the ODM.

**Comment by DougManuel** [comment]
I agree with all points that you raise. There is the benefit of having a separate configuration file for other parts and uses of the ODM. 

 In addition to configurations for mappers, there is likely a need for configuration files for other libraries such as sharing and validation. 

There is the benefit of having an explicitly defined configuration file as part of the dictionary. Let's plan on at least moving the current defaults to a new table or configuration file in the next major version update (something like `config.csv` or `config.json`.

**Comment by mathew-thomson** [comment]
Defaults have been removed from the dictionary for version 2. Flagging for future that these will be migrated over to a configuration file. Closing this issue for now.
