### ISSUE TITLE
Any plan to expand to Sequence data?

### ISSUE THREAD

**Issue by shioRyo** [Big-Life-Lab/PHES-ODM#172]
Currently, wastewater-based epidemiology is performed with not only qPCR but also next-generation sequence. Do you have any plan to expand the ODM that can deal with sequence data?

**Comment by DougManuel** [comment]
Yes. The proposal for an expanded dictionary is currently in review at PR https://github.com/Big-Life-Lab/ODM/pull/170. We encourage comments and reviews from everyone. 

We will leave this issue open until the final updated dictionary is incorporated into the main branch.

**Comment by DougManuel** [comment]
Feel free to add comments in this issue or the PR.

**Comment by mathew-thomson** [comment]
New info on sequencing and issues in capturing sequencing data in the ODM will now be addressed in the more specific issue of #225 - closing this issue for now.
