### ISSUE TITLE
Facilitate content translation

### ISSUE THREAD

**Issue by sorinsion** [Big-Life-Lab/PHES-ODM#175]
In all dictionaries please include a Language column that, together with the key for a value, will become the composite key that links to the other tables. This way, it will be extremely easy to switch from one language to another, both for inputs to and outputs from the database (you could collect data from a French template and present it in English, for example, or vice-versa). The keys, of course, will have to be repeated for values representing the same thing but in different languages

**Comment by mathew-thomson** [comment]
As mentioned in issue #86, `label`, `description`, and `instructions` will be translated as they're the relevant fields that are in english. French translations have already been done for most of these, and will be done for all items before launch. To add other languages, we'll need to complete the part list, and then look at translating the above mentioned pieces for all active parts.

**Comment by mathew-thomson** [comment]
You can look at the current ERD to see how implementation of this is working out, but the addition of a language and translation table, besides the part table allows for all relevant information to be translated with relative ease.
