### ISSUE TITLE
Include projection for coordinates / polygons

### ISSUE THREAD

**Issue by sorinsion** [Big-Life-Lab/PHES-ODM#176]
Please include a Projection or EPSG column in tables dealing with coordinates or polygons. Ottawa's coordinates are Lat/Long 45°15'1.591"/-75°48'3.895" in EPSG:4326 WGS 84 but they become X/Y 1508475.41/-190710.50 in EPSG:3978 NAD83 / Canada Atlas Lambert and if you don't know the projection these numbers are useless.

**Comment by NielsNicolai** [comment]
Should the model allow for different projections, or do we fix the reference system and people should adhere to this? The former is definitely more generic but it may lead to confusion for non-GIS experts?

**Comment by sorinsion** [comment]
Let's put as little pressure as possible on the users and let them use whatever projection suits them.
I can help with a conversion module that will take whatever coordinates or polygons and reproject them to, let's say, EPSG:4326 WGS 84. The only thing that should be mandatory would be for them to specify the EPSG code for each of the coordinates or polygons, if it's different from 4326. This should be made clear in the documentation.

**Comment by mathew-thomson** [comment]
The `Polygon` table now has a `geoEPSG` field for version 2. `lat` and `long` are only found in the site table, however. Should `lat` and `long` also be recorded in the `Polygon` table?

**Comment by mathew-thomson** [comment]
@sorinsion @DougManuel @jeandavidt - do we think that `lat` and `long` need to be added to the `Polygon` table as well, or are `geoEPSG` and `geoWKT` sufficient?

**Comment by jeandavidt** [comment]
`lat` and `long` can only hold one coordinate, whereas polygons, by definition, need at least three. `geoWKT` lets people enter a long string of coordinates in a standardized format. `geoWKT` (for the coordinates themselves) and `geoEPSG` (to indicate how the coordinates should be interpreted) are enough.

**Comment by mathew-thomson** [comment]
Amazing - thanks, @jeandavidt . I will close this issue for now then.
