### ISSUE TITLE
Internationalization/localization/accessibility

### ISSUE THREAD

**Issue by sorinsion** [Big-Life-Lab/PHES-ODM#177]
Please make sure that you employ UTF-8 character set throughout the development, to facilitate model adoption for non-Latin script potential users.

**Comment by jeandavidt** [comment]
I saw that `VariableCategory.csv` wasn't UTF-8, but I think everything else in the #170 PR, which will eventually become version 2 of the ODM, has the right encoding. I pushed a revision to the file, so it should be ok now.

**Comment by DougManuel** [comment]
See note from issue #184

**Comment by DougManuel** [comment]
See proposed language table in SQL format. from @sorinsion 
[Languages.sql.txt](https://github.com/Big-Life-Lab/ODM/files/7278459/Languages.sql.txt)
[newODMschema.sql.txt](https://github.com/Big-Life-Lab/ODM/files/7278461/newODMschema.sql.txt)

**Comment by mathew-thomson** [comment]
Issue noted and addressed, as above.
