### ISSUE TITLE
Implement mechanism to filter end-user accessible content based on data owner's grant of license and user ID (or similar)

### ISSUE THREAD

**Issue by sorinsion** [Big-Life-Lab/PHES-ODM#178]
Could we include in the model, FOR EACH MEASUREMENT, a "LicenseID" field, which lets us know what is the permissible extent to which one can use that measurement? 
If the field is empty or contains a set default value, we could consider the measurement as generally available to the public. If not, it should contain a key to a License table that could list the individual IDs, usernames, names or emails used for authentication, that will define who, effectively, has access to that particular measurement. This way we could easily implement a governance/data policy mechanism, by maintaining a License table wich contains the LicenseIDs as foreign keys and the individual IDs, usernames etc that are granted access to the data.
For example, under the ID 1 you could list all the authorized users from the Ottawa Public Health system, under the ID 2 all the users from ECDC and so on. Some regular expression mechanism could be implemented as well for the License table, so we could input *@ec.europa.eu under one ID or *@ohri.ca under other ID to grant generic use rights to users from certain organisations, if the email is used for authentication or can be derived from the user profile.

**Comment by DougManuel** [comment]
See proposed implementation [here](https://github.com/Big-Life-Lab/ODM/tree/sharing/sharing). I _think_ the proposal covers the intent and meets the requirements described. The proposal is PR https://github.com/Big-Life-Lab/ODM/pull/168 and discussion is welcomed in the PR or in this issue. 

Two notes on the current proposal:
- there is currently no detailed information for sharing/licence/access. This table could/should be added.
- the focus providing data custodians and generators (i.e. wastewater labs) support for sharing their data with others. The implementation, however, could be used by data repositories and others.

**Comment by GauriSaran** [comment]
Since `Measure` table is now the `Value` table, will the new licenseID column go into the `Value` table and will be linked to another `license` table? this will require us to add changes to code for sharing to query license table before granting sharing right and changes to specification.

**Comment by DougManuel** [comment]
The proposed sharing schema may not require a licenseID. Let's review the current proposal at our working group meeting. We can add licenceID if needed. 

Similar to the validation schema, we currently don't explicitly link the sharing schema to the value table with foreign keys. The measureID provides the explicit link if needed. There is a benefit for having a licenceID, but we had thought that we'll have a configuration file that stores information about what sharing or validation rules to use.

**Comment by mathew-thomson** [comment]
meeting with @rvyuha later today to begin orienting him to the dictionary - he'll then be working on and supporting the sharing and validation schemas with other team members. Flagging this issue for him as it will be important to consider in the sharing schema.

**Comment by mathew-thomson** [comment]
The sharing schema is underway, true, but also the question of licenseID and some other related issues were resolved (or at least addressed) by the addition of the dataset table (see issue #205 ). Shelving this issue for now.
