### ISSUE TITLE
Software licence

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#179]
The current licence for ODM is Creative Commons Attribution Share Alike 4.0 International. 

This licence was selected when ODM included only a dictionary and metadata. The current states that it is not recommended for programs or software. Specifications are underway for the ODM to include program code. 

Should we add an additional licence for the software? Is this even possible. It seems possible and reasonable because we are seeking to clarify, not change the licence. Any licence changes could and should be compatible with the current licence. See https://opensource.guide/legal/.

Licences for software that are similar to CCAS 4.0  include: [Aphace 2.0](https://choosealicense.com/licenses/apache-2.0/), [GPL 3.0](https://choosealicense.com/licenses/gpl-3.0/) and (AGPL 3.0)[https://choosealicense.com/licenses/agpl-3.0/].

**Comment by mathew-thomson** [comment]
@jeandavidt @martinwellman @yulric - any thoughts or input you can offer on this question?

**Comment by yulric** [comment]
@mathew-thomson Do you know how you want external users to use the code? For example, do you want to prevent them from changing it? Or do you want to allow them  to change it but give credit back to the ODM?

**Comment by mathew-thomson** [comment]
I'm not quite sure - I'm inclined to say hat people may be able to change it but still give attribution, but maybe @DougManuel has a more concrete answer?

**Comment by DougManuel** [comment]
I look a little closer and I think we should be good with what we have. We want people to do what they want with the code, but encourage folks to share back to ODM or with others.

**Comment by yulric** [comment]
@mathew-thomson @DougManuel  Here's a good table comparing all the licenses https://choosealicense.com/appendix/. Probably a good idea to verify all that info with somebody from OHRI.

**Comment by DougManuel** [comment]
The Choose A License site says, “Note that CC-BY-4.0 and CC-BY-SA-4.0 should [not be used for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).” 

But CC also [says](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), “Can I apply a Creative Commons license to software?

"We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering [licenses listed as free](https://www.gnu.org/licenses/license-list#SoftwareLicenses) by the [Free Software Foundation](https://www.fsf.org/) and [listed as “open source”](https://opensource.org/licenses) by the [Open Source Initiative](http://www.opensource.org/).
Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

_Version 4.0 of CC’s Attribution-ShareAlike (BY-SA) license is [one-way compatible](https://creativecommons.org/compatiblelicenses) with the [GNU General Public License version 3.0](https://www.gnu.org/copyleft/gpl.html) (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two. T[here](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3) are special considerations required before using this compatibility mechanism. Read more about it here._

Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, [see the relevant CC0 FAQ entry](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F).
While we recommend against using a CC license on software itself, CC licenses may be used for software documentation, as well as for separate artistic elements such as game art or music.”

**Comment by yulric** [comment]
So we should be using the GNU General Public License version 3?

**Comment by DougManuel** [comment]
I'll draft the addition of GNU GPL3 for software.

**Comment by mathew-thomson** [comment]
@DougManuel - have you had a chance to draft this?

**Comment by DougManuel** [comment]
We will generate most our software in separate repositories and use the GNU GPL3 for those repos.
