### ISSUE TITLE
new table request: measureSet

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#180]
Should we have a method to define sets of measures. This table could be used by a laboratory or organization to define measures that are routinely used or required in a wastewater program. 

Eventually, this table could be used to develop standard or minimal measures, as our field develops a consensus.

**Comment by mathew-thomson** [comment]
Do you think that this issue has been covered off by the current version 2 structure of `MeasureReport` and `MeasureSetReport`, @DougManuel, or do you think that it doesn't quite capture the aspect you envisioned?

**Comment by mathew-thomson** [comment]
MeasureSetReport (both as an ID and a table) cover off this issue.
