### ISSUE TITLE
Short names for measure attributes

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#181]
We require short abbreviations for measure attributes to allow the construction of names for the wide table. 

The names should be no more than 3 or 4 characters to allow them to be combined together into a unique 'full name'.

**Comment by mathew-thomson** [comment]
I updated the the site/Tables.csv file to remove the French information ahead of multi-language work, and added short full names for each table.

**Comment by mathew-thomson** [comment]
Also updated the variable file with variables names, and removed the French information ahead of multi-language work. Details [here](https://github.com/Big-Life-Lab/ODM/commit/57314794e9a322e0ba00746207af777b195d1a14#diff-8acec20aa6cff80cadaff24e1ce6ba3338253ff2eda0e6f37800905e4d322f19)

**Comment by mathew-thomson** [comment]
I believe this issue is covered off by issue #128 and #174 so I am closing this one for now. As mentioned in #174, currently all partIDs are well under 30 characters, but as wide names will be made from combining partIDs this will be important to consider.
