### ISSUE TITLE
Data input - suggested input tables and minimal data?

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#199]
1) Do we want an approach to create tables and recommended data collection? A: Yes. 

2) Do we want to create recommended: a) input tables and; b) minimal data set? 

Version 2 is moving away from specifically defined tables (location, sample, measure) to having these as properties of methods, measures and attributes. 

Up to now, we've added variables and attributes that are requested from stakeholders. The discussion has been that it is too early in the development of wastewater and environmental surveillance of SARS-CoV-2 to have required it minimal data. However, the list of variables is getting long....

**Comment by DougManuel** [comment]
Here is the minimal data from Research Coordination Network (RCN) on Wastewater Surveillance for SARS-CoV-2 is a U.S. National Science Foundation (NSF). https://pubs.rsc.org/en/content/articlehtml/2021/ew/d1ew00235j#tab1

**Comment by mathew-thomson** [comment]
We have developed input templates for most of the tables within the ERD. These would be a "full" data template, however, rather than minimal. What do we see as next steps for establishing a minimal data set? Or will minimal datasets be determined by users?

**Comment by mathew-thomson** [comment]
Important to include minimum metadata in this discussion as well. Pulled from Doug's comment in issue #224 :

The ODM strives to be robust and comprehensive, but it can also identify the minimum or required data.

Below is a list of recommended metadata from McClary-Gutierrez et al. 2021.

1. Let's indicate ODM parts for these minimum datasets. If requested, we can also create supporting documentation and tools, such as templates and data validation.

2. Folks, feel free to add other minimum data requirements to this issue.

McClary-Gutierrez, Jill S., Zachary T. Aanderud, Mitham Al-faliti, Claire Duvallet, Raul Gonzalez, Joe Guzman, Rochelle H. Holm, et al. “Standardizing Data Reporting in the Research Community to Enhance the Utility of Open Data for SARS-CoV-2 Wastewater Surveillance.” Environmental Science: Water Research & Technology 7, no. 9 (2021): 1545–51. https://doi.org/10.1039/D1EW00235J.

**Comment by Bahamyirou** [comment]
Hi @mathew-thomson. NML folk bring this question to me this weeks as they are working on data agreements with stakeholders. From the paper attached and my little knowledged on NML data and the ERD, can we say, the 4 main table below are important ? 

-	MeasureReport 
-	SampleReport
-	Site
-	DatasetID

**Comment by DougManuel** [comment]
ODM mandatory data is now completed for all tables. They are in the parts table in the headers {table name}Required.
