### ISSUE TITLE
Ontology approach and model entity relationship

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#200]
Version 2 has a range of objectives include better support for:

- Different specimen types. Extend beyond wastewater to include other environmental specimens (i.e. air and surface).
- More robust reporting of variants and mutations, including supporting different naming nomenclature (Panoglin and Nextclaid).
- Quality control and quality assurance, including the ability to report calibration curves
- Multilanguage support
- Improved data sharing and validation specifications 
- Improved ability to generate variable names and derived measures for wide tables from long tables
- Improved versioning and documentation

These changes necessitate an improved ontology approach and entity relationship.

**Comment by mathew-thomson** [comment]
As an update on this issue:

- Version 2 now includes `compartmentID` which allows users to specify whether a measure is done from air, surface, water, or population samples.
- The ability to measure mutations and variants (adding more presently), and record lineage and nomenclature (WHO, Panoglin, and Nextclade).
- Quality control measures and reporting are now built into the model, and we are looking at what parameters of a calibration curve are the most important to record.
- Multi-language support is built into the structure, with French being the only language besides english that is currently active.
- Data sharing and validation specifications are in development.
- Wide name metadata and variable generation are currently being developed and tested.
- Improved versioning and documentation are in the works.

As far as an improved ontology approach and entity relationship, however, what next steps did you have in mind, @DougManuel?

**Comment by DougManuel** [comment]
That is all for now. We can make formal links to existing ontologies. However, I think that should wait for after V2 is completed.
