### ISSUE TITLE
Sites/locations with sub-sites

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#201]
Surface testing often takes samples at different locations within a site. For example, the second floor of a lounge of a long-term care home. 

Suggest that the dictionary includes the ability to group sites or have sub-sites.

**Comment by mathew-thomson** [comment]
To accommodate this possibility, a parent-child relationship has now been built into the `Site` table (`siteID` and `parentSiteID`). This addresses and resolves the issue for now, and additional documentation and examples will be forthcoming.
