### ISSUE TITLE
Capturing Unquatifiable & Undetermined in the ERD

### ISSUE THREAD

**Issue by Bahamyirou** [Big-Life-Lab/PHES-ODM#210]
How to capture UQ and ND in the ERD:

**ND:  Undetermined, Ct value below the detection limit
UQ: Unquantifiable, Ct value exceeds the maximum value of the standard curve. There was a detect, but we cannot quantify it with certainty**

@mathew-thomson @DougManuel  @jeandavidt  I am wondering if it related to this https://github.com/Big-Life-Lab/PHES-ODM/issues/209

Asma

**Comment by mathew-thomson** [comment]
As with issue #209, these two levels have been added to the pCR quality variable for version 2. This should address this issue for now.
