### ISSUE TITLE
Date and time measures

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#211]
1) How to report date (and time) varies across different wastewater dictionaries and we have received requests for additional measures. 
2) There is a suggestion to split date and time into two variables from the current single variable. See #194 and the approach used by CDC NWSS.

Here is a list of suggested variables for date and time. 
**Sample collection times**
collectionDate - For grab samples, this is the date the sample was taken. Version 1 = dateTime
collectionTime - For grab samples, this is the date the sample was taken. Version 1 = dateTime
collectionDateStart - For integrated time-averaged samples this is the date the sample was started being taken. V1 = dateTimeStart
collectionTimeStart - For integrated time-averaged samples this is the time the sample was started being taken.  V1 = dateTimeStart
collectionDateEnd - For integrated time average samples this is the date the sample was finished being taken. V1 = dateTimeStart
collectionTimeEnd - For integrated time average samples this is the time the sample was finished being taken. V1 = dateTimeStart
sentDate - The date the sample was sent for analyses at a laboratory. Not in V1.

**Analyses or measurement times**
receivedDate - The date the sample was received at the laboratory for analysis. Not in V1.
analysisDate - The date the measurement was performed in the lab. V1 = analysisDate.
reportDate - The time the measurement was performed in the lab. V1 = reportDate.
lastUpdateDate - The date the measurement report was last updated. Not in V1.

**Comment by DougManuel** [comment]
Discussed at our working meeting. We will follow the above approach, but combine date and time into a single date-time measure.

**Comment by mathew-thomson** [comment]
As Doug states above, this has all been implemented as per discussion. analysisDate may be split into two fields (start and end) but otherwise this issue is closed.

**Comment by navus99** [comment]
This issue has been mentioned on **Open Data Model for Public Health and Environmental Surveillance**. There might be relevant details there:

https://odm.discourse.group/t/date-and-time-attributes/30/1
