### ISSUE TITLE
Site type - improved description required?

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#212]
ODM version 1 mixes a few concepts of describing a site. Other dictionaries also mix together concepts – NWSS is perhaps clearest, but NWSS lacks concepts in ODM. 

Do we want to review for ODM version 2? 

1) Concepts include: 
     - institution type. i.e. college, LTCF, airplane,
     - state of treatment or composition: raw wastewater, fecal matter, sludge, effluent, 
     - how the sample was taken: sewage pipeline, holding tank.

2) There are a few issues that we and others haven’t addressed. For example, 
     - sampling for a long-term care facility can include sampling from the street access (manhole) before AND after the LTCF. The two estimates are subtracted to give an estimate of viral recovery for the building. 
     - we may want an expanded list of how the sample was taken, such as ‘building take out’
     - surface and air testing has additional location information. For example, which floor, room or type of surface (ie. desk, floor). This last issue could wait for V2.1 but may be worth considering now.

3) Where are we going to put the additional attributes? The simple approach would be to add site attributes to the Site table. Some of the concepts of the site could be described as a method, such as the sampling method.

**Comment by DougManuel** [comment]
Samples: where, what and how

Suggested approach for version 2. 
 
- Ensure there is consistent use of naming concepts following a three step approach of where, what and how a sample was collected. 
	- where = `siteType`
	- what = `sampleMaterial`
	- how = `collection`
- Add categories from other dictionaries. CDC NWSS follows a similar approach to ODM (see below), and there are a few categories in CDC NWSS that are not in the ODM which we will add. 
- Add key categories for air and surface testing. 
	- We can expect air and surface categories to increase over time and more categories be added to later versions of the ODM.
- Identify categories for different compartments (air, surface and water) using the compartment attribute.
- Add `compartment` to each `siteType`. Compartments represent air surface and water (wastewater). 
- Use set to provide links and specificity between the three attributes (`siteType`, `sampleMaterial` and `collection`. For example, siteType = wwtpMuC combined wastewater treatment plant for combined sewage has an allowable sampleMaterial = sSludge (Sludge produced by secondary clarifiers) but sSludge would not be allowable for, say, retPond (retention pond) or surface testing of a school classroom floor.
	- Add sampleMat sets that are specific for each siteType category.
	- Add collection sets that are specific for each sampleMaterial category.

**Comment by DougManuel** [comment]
| Where |   | What |   | How
-- | -- | -- | -- | -- | --
ODM v1 | table = Site |   | table = Sample |   | table = Sample
  | variable = type |   | variable = type |   | variable = collection
  | wwtpMuC - wastewater treatment plant | rawWW - raw wastewater | grb - grab
  | airPln - airplane |   | sSludge - sludge produced by primary clarifiers | cdTP24h - proportional 24-h composite
  | ltcf - long term care facility |   |   |   |  
  |   |   |   |   |  
CDC NWSS v3 | WWTP_name |   | sample_matrix |   | sample_type
  | institution_type |   | raw wastewater |   | grab
  | correctional |   | primary sludge |   | 24-hr flow-weighted composite
  | long-term care - nursing home |   |   |   |  
  | airplane |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
OMD v2 | table = Site |   | table = sampleReport | table = sampleReport
  | part = siteType |   | part = sampleMaterial | part = collection
  | All ODM V1 and CDC NSWS v3 |   | all of OMD v1 and CDC NWSS v3 | all OMD v2 and CDC NWSS v3
  |   |   |   |   |  
  | Add compartment for each siteType |   | Add collection set that are specific for each sampleMaterial
  | Add sampleMat set that are specfic for each siteType |   |   |  
  |   |   |   |   |

**Comment by mathew-thomson** [comment]
I think this looks good and addresses all of the salient points first mentioned in the opening of this issue. My two questions, however, are:

1.  Why we need to add `compartmentID` for each `siteType`? `compartmentID` is currently only linked to `specimenID`, and the the the `MeasureReport` table. This makes more sense to me, since multiple types of measures (i.e. air, surface, water) can come from the same site. Unless I'm missing something. 
2. Are the rules and linkages between the three attributes (`siteType`, `sampleMaterial` and `collection`) have to be made explicit in the dictionary itself, or would it suffice to establish these linkages in the validation schema?

**Comment by mathew-thomson** [comment]
The implementation of 'sampleShed' besides siteType and the other sample report table and site table metadata fields covers off this issue.
