### ISSUE TITLE
disambiguation: `npmmov` and `nbrsv` 

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#214]
I've seen those variables used to mean both "concentration of sars-cov-2 normalized by [brsv or pmmov]" *and* "concentration of [brsv or pmmov]"

So:
1. Which option is the correct one? 🤔
2. Can we create variables for whichever option it isn't?

**Comment by DougManuel** [comment]
Both measures are used. The first, "concentration of sars-cov-2 normalized by.." is a unit where the measure is SARS-CoV-2 (allele, variant, mutation, etc.) The second, "concentration" is a when brsv or pmmov is the measure and the unit is 'gene copies per ml, etc.).

We address both these types of measures.
