### ISSUE TITLE
Population - Site population, polygon population, and population measures

### ISSUE THREAD

**Issue by mathew-thomson** [Big-Life-Lab/PHES-ODM#215]
It was brought up that population is an important aspect to capture, and it was initially suggested that this should be exclusively for 'Site' since it is a “slowly changing dimension” – seldomly changing, if ever unlike a real field measurement. As such, it could almost be treated as a fixed attribute, like zipCode. It’s also (by and large) an estimate, except for when referring to airplanes, cruises, etc. 

Everyone seems to agree that population should be an attribute of a site, but we also think that population could also be a Polygon attribute (e.g., if a polygon represents a public health region, it doesn’t necessarily have a site, however, the population living in that health region is important and should be recorded somewhere). 

We also think think that population should be a measure, as for some sites population changes day-to-day, and having population as a measure allows for this flexibility. Having population as a measure also allows for the possibility if bringing in outside data on things like case counts, etc. In this case, the 'group' would still be 'SARS-CoV-2', but the class would be 'population', and the measure would be 'cases', 'hospitalizations', or 'population counts'. Adding units like 'cumulative cases', 'cases per 100K', or 'cases among <5" allow for additional specificity and the capture of age and gender-based data. 

Currently it sounds like we'll be capturing 'population' in all three areas:

1. in the 'Site' table as 'populationServed'
2. in the 'Polygon' table as 'polygonPopulation'
3. as a measure and a class

This issue may also get confused with issue #123 when we start talking about design capacity and population equivalents, and whether and how these should be captured as attributes and/or measures.

@DougManuel @sorinsion @jeandavidt - does this capture the discussion to date? And further thoughts?

**Comment by DougManuel** [comment]
Having population in three area is flexible, robust and makes sense. However, we'll need to have good documentation.

**Comment by mathew-thomson** [comment]
It seems that folks are in agreement that this captures all the necessary points. The `Site` table now has `populationServed`, the `Polygon` table now has `polygonPopulation`, and there will be (a) measure(s) and potentially a class for population, but that discussion will take place in issue #129 since the main issues/questions here have been addressed.
