### ISSUE TITLE
Minimum or recommended metadata

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#224]
The ODM strives to be robust and comprehensive, but it can also identify the minimum or required data. 

Below is a list of recommended metadata from McClary-Gutierrez et al. 2021. 

1) Let's indicate ODM parts for these minimum datasets. If requested, we can also create supporting documentation and tools, such as templates and data validation. 

2) Folks, feel free to add other minimum data requirements to this issue.

McClary-Gutierrez, Jill S., Zachary T. Aanderud, Mitham Al-faliti, Claire Duvallet, Raul Gonzalez, Joe Guzman, Rochelle H. Holm, et al. “Standardizing Data Reporting in the Research Community to Enhance the Utility of Open Data for SARS-CoV-2 Wastewater Surveillance.” Environmental Science: Water Research & Technology 7, no. 9 (2021): 1545–51. https://doi.org/10.1039/D1EW00235J.

**Comment by mathew-thomson** [comment]
Closing this issue to merge it with issue #199
