### ISSUE TITLE
Building out sequencing metadata

### ISSUE THREAD

**Issue by mathew-thomson** [Big-Life-Lab/PHES-ODM#225]
(related to issue #172 ) We are working to allow for the inclusion of sequencing data and metadata in the ODM version 2. We have been chatting with members of CoVaRR Net's sequencing and bioinformatics pillar, as well as sequencers in Ontario's WSI program to make sure we are capturing all fields adequately. We are also looking at the work done by [PHA4GE](https://github.com/pha4ge/SARS-CoV-2-Contextual-Data-Specification) to see if we can integrate that work as well. Further comments or questions on sequencing can be documented in this thread.

**Comment by DougManuel** [comment]
Version 2 will include metadata for sequencing, mutations, allelles and gene regions. Measures are grouped into classes.



partID | partLabel
-- | --
allele | Alleles class
disease | Disease (human)
flowClass | Flow class
sequence | Genetic sequencing class
humClass | Humidity class
mutation | Mutations class
physical | Physical class
population | Population class
precipClass | Precipitation class
protein | Protein class
variant | Variants class
