### ISSUE TITLE
Separate Quality Flag columns for each quality flag or each type of quality flag

### ISSUE THREAD

**Issue by heather-i** [Big-Life-Lab/PHES-ODM#231]
In order to further automate our data management and reporting systems to be compatible with the Ontario Data Template based on the Open Data Model it would be helpful to split out the Quality Flag column in the WWMeasure tab to more easily support when there is more than one quality flag for a data point. According to the Protocol Evaluations for qPCR Performance used by the MECP and OCWA (attached), there are the following qualifiers:
B - background contamination observed (greater than 5 Cq away from samples; indicating that it would not affect quantification but it is present)
FI - failed inhibition
AI - addressed inhibition
ND - non-detect
J - concentration estimate extrapolated based on extending experiment-specific standard curve to the y-intercept
UJ - "Trace" amplification of target; concentration estimate extrapolated based on extending experiment-specific standard curve beyond the y-intercept

It would be easiest if all of these had their own column that could be true/false or if they were at least grouped into the type of quality flag. Ex. a column flags that correspond to concentration (ND, J, and UJ) since each sample can only be one of these and flags that correspond to inhibition (FI and AI) since each sample can only have one of these. 

I know this is very Ontario-specific so I understand if it is not possible to make these changes but if it is possible to include them and have them be optional for users of the Open Data Model who do not need these separated, then that would be wonderful.

Thanks!

<img width="667" alt="RTqPCRflowchart" src="https://user-images.githubusercontent.com/48387090/191512936-afaef746-16f8-450c-988a-63c1d5170eee.png">

[20220128_ProtocolEvaluationsqPCRPerformance_January2022.pdf](https://github.com/Big-Life-Lab/PHES-ODM/files/9616861/20220128_ProtocolEvaluationsqPCRPerformance_January2022.pdf)

**Comment by jeandavidt** [comment]
Another aspect of quality that was mentioned in the meeting was how to report LOD / LOQ for measures.

The dictionary is flexible in this regard, so it would probably be good to agree on a common way of doing things.

Here are all the options I can think of:

1. Add `loq` and`lod` values as rows in the `measures table.
1. Add `loq` and`lod` as methodSteps in the MethodSet table. Then, link the measures that use that assay with the correct methodSetID
1. Add `loq` and`lod` values as rows in the `measures table AND link them to the relevant lab measurement with a measureSetID. Thus, by looking through all the measures of a given measureSetID, we would find for each qPCR measurement:
    1. the qPCR measurement
    1. its associated lod
    1. its associated loq
1. Add a field to the `measures` table for `lod` and another for `loq`
1. If Option C is selected for the quality flags, `lod` and `loq`could be added as fields there.

The issue I see with lod and loq being in the quality table is that then it's hard to link the value to the right unit. 
If lod and loq are proporties in the measure, then the unit can be assumed to be the same as for the reported value.
If lod and loq are their own rows, aither in MethodSteps or measures, they can have their own unit without having to worry about the unit used by specific measurements.

**Comment by DougManuel** [comment]
Just a clarification that this issue discussion is referencing versions 1.1 and 2.0. 
@heather-i references are mostly about v1.1. @jeandavidt references are mostly about version 2.0.

Version 2.0 expands the dictionary and the model quite a bit. The name change from `WWMeasure` (wastewater measure) to `measures` reflects that measures can be for water, air or surface and more robustly include population measures (testing, hospitalization, etc.).

In version 2.0:
1) LOD and LOQ change from headers within the `measures` tables to what is described by @jeandavidt in this issue (a row in the measure table linked to measures using `measureSetID` or within the `methods` table). There are a few reasons for this change. Most notably, `LOD` and `LOQ` are relevant to specific measures, such as PCR measures. There is a considerable increase in measures, such as chemical and physical properties, where LOD and LOQ don't apply.

2) Quality sets (`qualitySet`) are introduced. Currently, four quality sets are described, but more can be added at any time: Generic Quality Flag Set; PCR Quality Set; Sample Quality Set; Sequencing Quality Set. Each measure can have a quality set. 

As an aside, in Version 2.0, there are also aggregation sets (`aggSet`), and unit sets (`unitSet`). So, each measure has an aggregation set, unit set and quality set. A unit set for temperature (degrees celsius) is different from a unit set for SARS-CoV-2 N1 gene region detection by PCR (gene copies per l, gene copies per copies of PPMoV, etc.)

3) Measure sets (`measureSetID`) are introduced. Measures sets allow groups of measures to be associated with each other. There are several use cases for measure sets, but they are generic and flexible. Associating LOQ and LOD to a group of measures was one identified use case. Other use cases include: 
- variants - when performing variant testing, there may be multiple variants identified, etc.
- controls - generating and reporting Ct curves or performing dilutions, spike samples, etc. 

Measures and samples can also be grouped, but there are slightly different considerations. Samples have the provision for having parent, child, combined samples, etc. Methods have methodSteps that can be grouped, and then groups can be combined. For example, there could be several RNA extraction steps that can be grouped together and then added with other groups of steps for, say, concentration, PCR, etc. to form an overall assay method.

**Comment by DougManuel** [comment]
Remember that we’ll want our quality measures to work in both ‘long’ and ‘wide’ data formats. I don’t foresee major issues with any proposed solutions, but there are a few considerations and implementation issues. We’ll likely want the core ODM development team to review how to generate long names before we sign off on a reporting approach. 

Long data is the main ODM data format, but version 2 provides better support for wide tables with an explicit formula for generating wide names. Variable names for wide tables can get very long because the names are a connotation of attributes. See below. This means that we’ll want short part names for quality measures.

The figure below is preliminary and not quite up-to-date. Regardless the figure informs the general approach. 

<img width="500" alt="Screen Shot 2022-09-25 at 3 40 19 PM" src="https://user-images.githubusercontent.com/13246138/192162148-9412a989-61c7-4673-82f4-43c7e36e4c28.png">

<img width="500" alt="Screen Shot 2022-09-25 at 3 40 28 PM" src="https://user-images.githubusercontent.com/13246138/192162152-b488ebd9-2a62-44da-8249-352b9a723ce5.png">

<img width="500" alt="Screen Shot 2022-09-25 at 3 40 37 PM" src="https://user-images.githubusercontent.com/13246138/192162157-0884b15c-b4ae-471c-8edc-c9b7478b404c.png">

**Comment by DougManuel** [comment]
For Option B, what is the implementation? Do we need key:value pairs. Maybe even key:value:units (for numerical quality measures).

1) Key:value pairs: `qf1_partID`, `qf1_value`, `qf2_partID`, `qf2_value`. 
`qf1_partID`= J, `qf1_value` = TRUE.

2) Use the partID as the name, and then the entry is the value. `qf1_J`
`qf1_J` = True.

3) Have the quality measure as the value and assume TRUE. `qf1`
`qf1` = `J`

The above approaches also need to work for quality measures that are not Boolean but real numbers: measures such as LOQ, concentration estimate, etc. Key value pairs for these measures, and also implementation 2. The value measures need an accompanying unit and maybe also an aggregation.

A challenge for implementation 2 is a proliferation of qf1_ variables as headers. Remember that there are measures other than PCR. Currently, in version 2, there are 22 quality measures, which would mean adding 22 variable headers to the measuring table -- of which most are not relevant for any one measure. Now you've got a wide-table format instead of a long-table format.

**Comment by jeandavidt** [comment]
So for version 2.0, we propose going for option C:
* A new quality table is created
* Each row of the quality table creates a new quality flag
* Quality flags can be linked to either of the following (1 per row): measure report, measure set report, sample report
* Any sample, measure set or measure can have as many flags as required

**Comment by jeandavidt** [comment]
But a thing we might want to do is to allow one measure to belong in many sets (say, a set of replicates and a set of all the measures that were done with the same calibration curve). For that, we need to turn the relationship between measures and measureSets from n:1 to n:n

n:n linkages require a lookup table. Thus, the setup would be the following:
* The measureReport Table loses its measureSetReportID field
* The measureSetReport table is still there to store the unique ID of each new set. We can also choose to give names to the sets and / or a type (e.g., qualitycontrolSet or ReplicateSet or whatever)
* A new lookup table (maybe, MeasureSetHasMeasures) that has no primary key field and 2 foreign keys as fields (MeasureSetID, measureReportID)

I put these changes into the ERD for review and discussion

**Comment by DougManuel** [comment]
All points by @jeandavidt look good. 

The first task we need to complete is how to store data that address required use cases for quality measures. What @jeandavidt suggested does address use cases that have been discussed - in particular, the main issue thread and the ability to store multiple quality measures. 

The second task is to recommend data easy data collection for common uses. @heather-i has a good point that Option B is easy to implement and understand for many users and use cases. 
- As an interim step, we could implement Option B for version 1.2 and then have a more robust qualityFlag table for version 2. 
- In practice, people could generate input templates or data collection that has option B as wide variable names. 
     - mixing wide and long variables works if people use a data collection table for selected measures such as PCR alleles, but the solution is not robust for multiple measure with different qualityFlagSets.
     - we probably want default ODM templates that are robust and so they wouldn't include this practice.

**Comment by DougManuel** [comment]
We will need to decide whether we want the 'reportable' attribute and how that would be used. From the discussions:
- `reportable` is an important attribute that we want to keep. This attribute is widely requested and it is also a helpful flag that there is or should be a corresponding entry in the qualitySet table.
- There is the greatest support to have as a boolean. True = 'report'; False= 'don't report'. However, some people would prefer more categories.
- It is possible to have a more nuanced summary reportable attribute in the qualitySet table and to support a nice, clean boolean 'reportable' attribute in the measure and sample tables.

**Comment by DougManuel** [comment]
I tend to support updating the measureSetReport table to allow n:n, but we haven't received many requests that require this more robust structure. However, the more robust structure:
- is more consistent with the approach of the ODM model. 
- similar to qualityFlag, we could have a flag in the measures table that says the measure is part of a measureSet. This helps users know to add entries to measureSet (if data generators) or look at the measureSet table (if data users). 
- for data storage, we would remove mesaureSetReportID from the measures table. But similar to quality flags, data input tables could have this measure for users who have only one measureSet for any specific measure. 

Regardless, the idea to add additional descriptors makes sense (e.g., qualitycontrolSet or ReplicateSet or whatever) and those descriptors could be added to the existing measureSet table.

I am not sold on MeasureSetHasMeasures. I find the 'has' tables are conceptual great, but many people are not familiar with them or their application.

**Comment by mathew-thomson** [comment]
Thank you @jeandavidt for laying things out so eloquently, and to build on @DougManuel 's point re: `reportable` - one thing that was brought up in our discussion was to continue to use `reportable` in the `measures` table and add it to the `samples` table. To add potential levels of nuance, while still maintaining a final ease of interpretation, a `severity` column in the proposed `qualityReports` table with a traffic-light-style tier system. This wouldn't replace `reportable`, and would be optional, but provides some additional detail on how important a given flag is outside the final yes-no reportable decision. 

I also am somewhat conservative about blowing up the `measureSets` structure to allow for n:n relationships with measures, but if the labs are supportive of this kind of infrastructure then I think it would be great to build it in before we launch v2.0.

**Comment by DougManuel** [comment]
Version 2 will have a specific quality table that can record multiple quality measures for any sample or measure.
