### ISSUE TITLE
License categories for dataset table and partID = measureLic

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#244]
See Discourse https://odm.discourse.group/t/license-category-set/107.

Add common license categories. 
- pro: more consistent than notes.
- con: we'd need a free text field anyway because we probably won't have an exhaustive list.

**Comment by mathew-thomson** [comment]
This was added for version 2.2. To see the full list of supported license options for the measure license and dataset license fields, see the `sets` table where `setID` == `licSet`.
