### ISSUE TITLE
Add normalization measures

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#252]
Addd "creatinine (CRE), 5-hydroxyindoleacetic acid (5-HIAA), caffeine (CAF) and its metabolite paraxanthine (PARA)". 

See https://www.medrxiv.org/content/10.1101/2022.03.14.22272359v1

**Comment by mathew-thomson** [comment]
All these measures have been added, and will be all visible in the 2.2.1 patch release coming later today.
