### ISSUE TITLE
Parts Table order

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#254]
The parts table can be used to assemble the definition of every table in the ODM. This can be done for a given table by:

- identifying the parts table columns that have to do with the table we are looking at. For any given table, those'll be:

  - `tableName`
  - `tableNameRequired`
  - `tableNameOrder`

- filtering the all parts such that only those with values in ["header", "fK" or "pK"] in the `tableName` column should yield a list of all the columns of table `tableName`. Moreover, the values in the `tableNameOrder` should all be between 1 and the number of filtered parts, and the values in `tableNameOrder` should be unique and monotonically increasing.

When I did this on the parts table of release v2.1.0, all tables passed this test, except for the "parts" table itself.

Digging deeper, I found these issues:
- `partsOrder` value `15` is missing
- `partsOrder` value `24` is there twice (`protocolStepsRequired` and `protocolRelationshipsRequired`)
- `partsOrder` value `46` is missing
- `partsOrder` value `56` is missing
- `partsOrder` value `66` is there twice (`translationsOrder` and `partsOrder`)
- `partsOrder` value `83` is missing

@mathew-thomson @DougManuel should I submit a PR with a new numbering? Or maybe this should be fixed in the main Excel file instead?

Thanks!

**Comment by mathew-thomson** [comment]
Hey JD - thanks for catching this! This is something that needs to be fixed in the main excel working file, you're right. Are you comfortable fixing this, or would you rather someone else go through using your above list?

**Comment by jeandavidt** [comment]
I'll go into the Excel file later this morning and let you know when I'm done ^^

**Comment by jeandavidt** [comment]
It's done ✅
