### ISSUE TITLE
Restructure metadata in table or object format

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#29]
Should we move from an .MD document to a table or object? 

We can generate the md from a table or object and then have better alignment with the ERD and SQL docs.

**Comment by hswerdfe** [comment]
what would the format of such a table be? 

- table_name
- column_name
- type
- primary_key
- allowed value
- description

**Comment by mathew-thomson** [comment]
The current structure of the documentation leans into this concept with a series of tables/an excel sheet from which templates and documentation are automatically generated. See the documentation branch and the dictionary excel file in the OSF.io repository for more details.
