### ISSUE TITLE
Line level case data, could be added

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/PHES-ODM#35]
Line level case data, could be added to the data model with an additional table.
`caseID`  case-id of the reporter.
`reporterID` 
`postalCode_3_6` 
`age`
`sex`
`onsetDate`
`repordedDate`
`recoveryDate`
`DeathDate`

**Comment by DougManuel** [comment]
At some point, we'll want to draw a line between what we are collecting in wastewater data and what would be linked with external case data. 

The most critical issue is allowing a linkage between wastewater data and case data. That linkage typically happens through a residential address that is coded using postal code/zip code. Yes, there are many alternative situations, but in practice, the residential postal code and geo bounding box is the crosswalk. 

Suggest adding `postalCode_3_6_list` to Polygon table. The data ype for this variable a list or array.

**Comment by NielsNicolai** [comment]
I agree with Doug! 
If I understand it correctly, you want to use `postalCode_3_6_list` to have a list of all postal codes (3 or 6 digits) that a polygon would encompass?

**Comment by jaizkibel2** [comment]
I agree, too. And this is very important. But heads up that the postal codes geocoded file is proprietary data of Canada Post, and when we tried to that at STC we were told that was exactly an unauthorized use of the file. We don' t have a good solution for now.

**Comment by DougManuel** [comment]
I know this data well. I'll clarify and take care of this issue.

**Comment by mathew-thomson** [comment]
I wonder if this issue is still relevant? From the discussion above, it would seem to me that folks are agreeing that the model shouldn't hold line-level case data. For these "population measures" though, it seems to me that the geographic linkage issue has now been resolved because there is a direct link between the MeasureReport table and the Polygon table.

@DougManuel let me know if you disagree, but otherwise I may close this issue soon.

**Comment by mathew-thomson** [comment]
It's been decided to avoid holding line-level case data, and provisions for storing population-level case data are already present in the model. As stated above, the geographic linkage issue has now been resolved because there is a direct link between the MeasureReport table and the Polygon table.
