### ISSUE TITLE
Recommneded Wastewater Surveillance Sampling/Handling/Storage Protocol

### ISSUE THREAD

**Issue by vipileggi** [Big-Life-Lab/PHES-ODM#62]
What is a sound recommended wastewater surveillance sampling protocol that adequately addresses issues of sample collection, handling, storage, archiving, etc.... and can be adopted broadly.

**Comment by vipileggi** [comment]
Found this from the New Jersey DEP at [NJ DEP Recommendations](https://www.nj.gov/dep/dwq/pdf/COVID19_DWQ_Guidance_for_WW_Collection_&_Analysis_20200720.pdf) that addresses some of the key points on the related issue

**Comment by DougManuel** [comment]
This is an important issue but I'm not sure if we can address for V1.0. 

@vipileggi I'm assigning to you and tagging v1.0.1. Please feel to reassign or upgrade to v1.0.0. Folks at NML may be able to help since they have quite a few variables for temperate to reflect samples moving around the country. @cmangat can you help?

What we need, I think, is a diagram of a timeline from sample collection to test result publication. This timeline would identify the different time variable (quite a few) and any additional variables that need to be collected at different stages.

**Comment by DougManuel** [comment]
See also https://github.com/Big-Life-Lab/covid-19-wastewater/issues/25.

**Comment by vipileggi** [comment]
@DougManuel , @hswerdfe, @cmangat and @NielsNicolai FYI we're proceeding with the Ontario Template (attached Jan 19/21 version) to be sent out likely today to be shared with labs since front runners (Ottawa, Waterloo, Windsor, Ontario Tech, Guelph and Ryerson) will start to populate it immediately. The Excel Workbook is attached for your preview. I've indicated to Bahar/Steven that it will change based on work on the ODM v1.0 (v1.1...) but we (MECP via Hub/Esri/OHRI) can make labs transition to new version seamlessly  via Hub scripts or MECP-Hub-Esri-Geomatics support.
[Ontario Template - Ottawa Data Model Version 1.0 Jan_19_2021.xlsx](https://github.com/Big-Life-Lab/covid-19-wastewater/files/5835837/Ontario.Template.-.Ottawa.Data.Model.Version.1.0.Jan_19_2021.xlsx)

Extremely busy with other time-sensitive MECP work but will update issues as time permits.

On 'Sampling' part of this issue, one key addition/change related to this is found in the 'Definition of Terms' worksheet (and Sample worksheet of the Ontario Template) proposed and for discussion (quote below) is the 'sample MethodCollection' which at this time based on internal MECP discussion we need to consider and allow for the following seven methods (still under internal discussion) but pushing it out now due to 'urgent demand':

> 'sampleMethodCollection': method used to collect representative wastewater or primary sludge samples. Seven methods are available: 'compTimeProp24h' (M1) to indicate a composite time proportional 24-hour composite sample generally collected by an autosampler; 'compFlowProp24h' (M2) to indicate a composite flow proportional 24-hour composite sample generally collected by an autosampler; 'grabComp8h' (M3) to indicate a grab 8-hour composite with 8 grab samples taken once per hour, generally manually; 'grabComp3h' (M4) to indicate a grab 3-hour composite with 3 grab samples taken once per hour, generally manually; 'grabCompSample3' (M5) to indicate a grab-composite sample composed of 3 separate grab samples (5L or more); 'grabSample1' (M6) to indicate a single large (10L or more) representative grab sample and 'grabPrimarySludge' to indicate a single large representative primary sludge sample following primary sedimentation at the WWTP without mixing of other sludge types. Note: Sample collection method M1 or M2 are to be used at all WWTPs to collected influent wastewater. Sample collection in a sewershed is to follow method M1 or M2 where ever possible. For collection in a sewershed when a composite sampler is not feasible methods M3, M4 or M5 are acceptable alternatives. Under severe field conditions in the sewershed where M3, M4 or M5 cannot be safely implemented M6 is allowed. For primary sludge collection M7 is to be used.

**Comment by vipileggi** [comment]
Got a message that something went wrong with previous message. Just adding corrected OT- Excel Workbook @DougManuel , @hswerdfe, @cmangat and @NielsNicolai 
[Ontario Template - Ottawa Data Model Version 1.0 Jan_19_2021 am.xlsx](https://github.com/Big-Life-Lab/covid-19-wastewater/files/5835898/Ontario.Template.-.Ottawa.Data.Model.Version.1.0.Jan_19_2021.am.xlsx)

**Comment by DougManuel** [comment]
I've added the template to the template folder. See renamed as [Ontario_Template_ODM_1.0.xlsx](https://github.com/Big-Life-Lab/covid-19-wastewater/blob/dev/template/Ontario_Template_ODM_1.0.xlsx)

see also #13.

**Comment by jaizkibel2** [comment]
I think we have a sampling protocol that includes handling and shipping instructions. I see if we can share it.

**Comment by vipileggi** [comment]
Hi @jaizkibel2 https://github.com/Big-Life-Lab/covid-19-wastewater/issues/62#issuecomment-763993418 any news on potentially sharing this? thanks

**Comment by mathew-thomson** [comment]
Recommended protocol seems to be something that's shifting a fair bit across Canada (and the world) and something that needs to be brought up in larger QA/QC and program evaluation conversations. This is currently out of scope for the ODM data dictionary. Version 2 allows users to store detailed information on their protocol so that it can be reviewed along with their results, so it circumvents the issue for now.
