### ISSUE TITLE
Visual diagram for pooled sample

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#74]
To explain the relationship between different samples.

See #34.

**Comment by NielsNicolai** [comment]
Hi @DougManuel Would a figure like this one on the [USA Today webpage](https://eu.usatoday.com/story/opinion/2020/08/25/how-pooled-testing-covid-19-may-help-schools-reopen-safely-column/3399508001/) do?

**Comment by jeandavidt** [comment]
[Would this do the trick?](https://ulavaldti-my.sharepoint.com/:i:/g/personal/jdthe3_ulaval_ca/EWHsvqobX0ZBhubkCuhpH5IBIrughmrh4rKzPl4I_jB8XQ?e=5VEeew)

**Comment by DougManuel** [comment]
Let's implement. I'm not sure where it should best go. We need a much-improved documentation section. I started a branch with documentation from MECP. 

Do you have suggestions? We could temporarily put somewhere until we can more robustly rethink documenation.

**Comment by mathew-thomson** [comment]
As an update to this thread, @jeandavidt generated a new diagram to illustrate the pooled and parent-child relationships of samples, but we are now potentially revisiting/restructuring that diagram and approach as we aim to include provisions in the ODM for sample replicate type (issue #94 )

**Comment by mathew-thomson** [comment]
@jeandavidt has written out some documentation on the question of replicates and parent-child relationships within the ODM. This includes a visual diagram. This can be found here: https://jeandavidt.notion.site/Child-samples-4b8b7496e139476cbcb086bcfe3e7052
