### ISSUE TITLE
Additional normalization methods

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#76]
Identify and add additional normalization methods and markers:
- ammonia

**Comment by mathew-thomson** [comment]
Update that ammonium nitrate has been added as a measureID in version 2

**Comment by mathew-thomson** [comment]
Ammonium nitrate has been added as a measureID in version 2, and is present with other normalization markers - namely, pmmov, F-Specific RNA bacteriophages, and crAssphage. Closing the issue now.
