### ISSUE TITLE
Ensure support for English and French 

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#86]
Two issues:

1) Current documentation is in English. We need to add French. Suggest this is another reason to move document into a table (csv).

2) Some text data will be entered in French such as description, notes, etc. What is the best approach to ensure data in two languages can be easily used?

**Comment by NielsNicolai** [comment]
Which parts of the data model should and should not be translated. For example, do we translate variable names, drop-down options, etc.? 

@jeandavidt

**Comment by hswerdfe** [comment]
@NielsNicolai  suggest starting with the dev branch. there is a table `Tables.csv` and `Variables.csv` and `VariableCategory.csv`
the metadata is generated from that, and it already has columns for french. It was "cereal box" translated with deepl.com

**Comment by hswerdfe** [comment]
@NielsNicolai I propose the following way forward.
  * review 3 tables listed above
  * ensure that french in existing columns is correct
  * decide if we need more french columns, like maybe the `Desc` columns are only english now
  * modify `R ` code that generates the metadata file to generate french and english versions of the documentation file.

**Comment by DougManuel** [comment]
I also suggest:
- category labels in English and French. (Many will be the same as the description). 
- category values. @hswerdfe and I had a brief discussion. I still think these will be needed and users will create values if we don't.

**Comment by NielsNicolai** [comment]
Just making sure that @jeandavidt also gets the above information.

**Comment by jeandavidt** [comment]
Hi!
I went to work on this today, and here is what I have so far:

For Variables.csv:
- Corrected the french in variableLabel_fr,
- Added variableDesc_fr,

For Table.csv:
- Corrected tableLabel_fr
- Added tableDesc_fr,

For VariableCategory.csv:
- Added desc_fr

As for the last bullet point in @hswerdfe's post, I'm afraid my R is a bit rusty 😅 I can have a stab at implementing the changers in the code, but it would really help if someone could walk through it with me first :) 

Do I also understand correctly from @DougManuel 's last comment that the column "variableValue" from VariableCategory.csv should be renamed "variableValue_en" and that a french version should be created?

Thanks!

**Comment by hswerdfe** [comment]
@jeandavidt did you push to `dev`? my R is sharp. If you push I can do the update. as for the _en... I am unsure.

**Comment by jeandavidt** [comment]
Hmm, I think I may have made a mistake - I just pushed to dev, but should I have created a pull request instead? Sorry, I'm still not used to collaborating in open source projects in github 😅

**Comment by hswerdfe** [comment]
@jeandavidt pull request is probably best. but its cool its just `dev`. I'll try to do an auto generation of the En and fr metadata files.

**Comment by mathew-thomson** [comment]
Closing this issue since it duplicates issue #175 in some important ways. Currently only label, description, and instructions will be translated as they're the relevant fields that are in english. French translations have already been done for most of these, and will be done for all items before launch.
