### ISSUE TITLE
Polygon file format

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#87]
Should there be a wider range of formats for the polygon for the wastewater spacial data?

- AArcGIS Web Service / AGOL link
- Open Data (API)
- File-geodatabase (.fgdb) or shape file (.shp)

**Comment by diegoripley** [comment]
Hi @DougManuel, 

Have you thought about using the GeoPackage file format? [1] In short, it is an SQLite database file that can contain geospatial information and is supported by all major software (ex. Esri’s ArcGIS Pro, QGIS, GeoServer, etc.) [2].

Based on what I see in [3], [4], and [5], the “related tables extension” [6] would be perfect to bring your data into the geospatial realm. Let me know if you need any help, I would be more than happy to contribute! 😊

[1] https://www.loc.gov/preservation/digital/formats/fdd/fdd000520.shtml
[2] http://www.geopackage.org/implementations.html
[3] https://github.com/Big-Life-Lab/covid-19-wastewater/blob/main/src/wbe_create_table_SQLITE_en.sql
[4] https://github.com/Big-Life-Lab/covid-19-wastewater/blob/main/template/WBE.db
[5] https://github.com/Big-Life-Lab/covid-19-wastewater/blob/main/data/wwMeasure.csv
[6] http://docs.opengeospatial.org/is/18-000/18-000.html#DesignClause

**Comment by DougManuel** [comment]
I posted the question but I have not kept UTD on spatial data formats. 

Do others have an opinion? @jeandavidt @NielsNicolai @martinwellman ?

**Comment by mathew-thomson** [comment]
Discussed this issue in today's ODM meeting, and it was expressed that the EU almost universally uses shapefile. Although we currently use WKT, it was raised that it may be beneficial to look at geoJSON. Ultimately there are a lot of contenders, including GeoPackage mentioned above. It is important to be flexible, though, and packages do exist to transform between file types (example: https://gdal.org/programs/ogr2ogr.html). The nice thing about GeoJSON is that it's open. We'll need to just pull the trigger and make a decision on this at some point. @DougManuel

**Comment by diegoripley** [comment]
My 2 cents.

Focus on creating test data first, worry about file format second: spatial and attributes, make it look as realistic as possible (ex. values within allowable ranges). Ogr2ogr can convert between different file formats with a single command, so shapefile or GeoJSON can easily be exported.

I advise to keep everything as close to internal as you can (GeoPackage which is SQLite, spatial as wkt or wkb if I recall correctly) and convert to shapefile or any other formats afterwards. Data guys will love you.

If using shapefile internally make sure to read up on field length limitations [1]. Once you read up on file formats you will see they all have their place on the table, depending on use-case. 

[1] https://www.loc.gov/preservation/digital/formats/fdd/fdd000280.shtml
