### ISSUE TITLE
Reporter affiliation

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/PHES-ODM#97]
Currently, there is no field in the reporter table to describe the organization for which a named reporter is working. I would therefore suggest separate `name` and `organization` fields.

**Comment by DougManuel** [comment]
Let's add.

**Comment by NielsNicolai** [comment]
It would make sense to link the organization to the lab using the `labID`. Would that not be better?

**Comment by mathew-thomson** [comment]
@DougManuel - could we call this issue resolved?

**Comment by mathew-thomson** [comment]
We now have an 'organizationID' in the 'Organization' table, which connects to the 'MethodReport' and 'Contact' tables, accomplishing the goals of the above conversation, just using slightly different names. (reporter=contact, lab=organization, etc.)
